package com.tdil.ljpeugeot.dao.impl.sqlserver;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tdil.ljpeugeot.dao.NativeAppDAO;
import com.tdil.ljpeugeot.model.NativeApp;
import com.tdil.ljpeugeot.model.NativeAppExample;
import java.sql.SQLException;
import java.util.List;

public class NativeAppDAOImpl implements NativeAppDAO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public NativeAppDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int countNativeAppByExample(NativeAppExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("dbo_NATIVE_APP.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int deleteNativeAppByExample(NativeAppExample example) throws SQLException {
		int rows = sqlMapClient.delete("dbo_NATIVE_APP.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int deleteNativeAppByPrimaryKey(Integer id) throws SQLException {
		NativeApp _key = new NativeApp();
		_key.setId(id);
		int rows = sqlMapClient.delete("dbo_NATIVE_APP.deleteByPrimaryKey", _key);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public Integer insertNativeApp(NativeApp record) throws SQLException {
		Object newKey = sqlMapClient.insert("dbo_NATIVE_APP.insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public Integer insertNativeAppSelective(NativeApp record) throws SQLException {
		Object newKey = sqlMapClient.insert("dbo_NATIVE_APP.insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	@SuppressWarnings("unchecked")
	public List<NativeApp> selectNativeAppByExample(NativeAppExample example) throws SQLException {
		List<NativeApp> list = sqlMapClient.queryForList("dbo_NATIVE_APP.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public NativeApp selectNativeAppByPrimaryKey(Integer id) throws SQLException {
		NativeApp _key = new NativeApp();
		_key.setId(id);
		NativeApp record = (NativeApp) sqlMapClient.queryForObject("dbo_NATIVE_APP.selectByPrimaryKey", _key);
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int updateNativeAppByExampleSelective(NativeApp record, NativeAppExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("dbo_NATIVE_APP.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int updateNativeAppByExample(NativeApp record, NativeAppExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("dbo_NATIVE_APP.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int updateNativeAppByPrimaryKeySelective(NativeApp record) throws SQLException {
		int rows = sqlMapClient.update("dbo_NATIVE_APP.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	public int updateNativeAppByPrimaryKey(NativeApp record) throws SQLException {
		int rows = sqlMapClient.update("dbo_NATIVE_APP.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.NATIVE_APP
	 * @mbggenerated  Fri Apr 04 22:11:39 ART 2014
	 */
	protected static class UpdateByExampleParms extends NativeAppExample {
		private Object record;

		public UpdateByExampleParms(Object record, NativeAppExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}