package com.tdil.ljpeugeot.dao.impl.sqlserver;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tdil.ljpeugeot.dao.StateDAO;
import com.tdil.ljpeugeot.model.State;
import com.tdil.ljpeugeot.model.StateExample;
import java.sql.SQLException;
import java.util.List;

public class StateDAOImpl implements StateDAO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public StateDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int countStateByExample(StateExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("dbo_STATE.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int deleteStateByExample(StateExample example) throws SQLException {
		int rows = sqlMapClient.delete("dbo_STATE.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int deleteStateByPrimaryKey(Integer id) throws SQLException {
		State _key = new State();
		_key.setId(id);
		int rows = sqlMapClient.delete("dbo_STATE.deleteByPrimaryKey", _key);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public Integer insertState(State record) throws SQLException {
		Object newKey = sqlMapClient.insert("dbo_STATE.insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public Integer insertStateSelective(State record) throws SQLException {
		Object newKey = sqlMapClient.insert("dbo_STATE.insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	@SuppressWarnings("unchecked")
	public List<State> selectStateByExample(StateExample example) throws SQLException {
		List<State> list = sqlMapClient.queryForList("dbo_STATE.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public State selectStateByPrimaryKey(Integer id) throws SQLException {
		State _key = new State();
		_key.setId(id);
		State record = (State) sqlMapClient.queryForObject("dbo_STATE.selectByPrimaryKey", _key);
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int updateStateByExampleSelective(State record, StateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("dbo_STATE.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int updateStateByExample(State record, StateExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("dbo_STATE.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int updateStateByPrimaryKeySelective(State record) throws SQLException {
		int rows = sqlMapClient.update("dbo_STATE.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	public int updateStateByPrimaryKey(State record) throws SQLException {
		int rows = sqlMapClient.update("dbo_STATE.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.STATE
	 * @mbggenerated  Sun Feb 02 21:48:07 ART 2014
	 */
	protected static class UpdateByExampleParms extends StateExample {
		private Object record;

		public UpdateByExampleParms(Object record, StateExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}