package com.tdil.lojack.dao;

import com.tdil.lojack.model.WebsiteUser;
import com.tdil.lojack.model.WebsiteUserExample;
import java.sql.SQLException;
import java.util.List;

public interface WebsiteUserDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int countWebsiteUserByExample(WebsiteUserExample example)
			throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int deleteWebsiteUserByExample(WebsiteUserExample example)
			throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int deleteWebsiteUserByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	Integer insertWebsiteUser(WebsiteUser record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	Integer insertWebsiteUserSelective(WebsiteUser record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	List<WebsiteUser> selectWebsiteUserByExample(WebsiteUserExample example)
			throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	WebsiteUser selectWebsiteUserByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int updateWebsiteUserByExampleSelective(WebsiteUser record,
			WebsiteUserExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int updateWebsiteUserByExample(WebsiteUser record,
			WebsiteUserExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int updateWebsiteUserByPrimaryKeySelective(WebsiteUser record)
			throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBSITEUSER
	 * @mbggenerated  Thu May 02 23:36:09 ART 2013
	 */
	int updateWebsiteUserByPrimaryKey(WebsiteUser record) throws SQLException;
}