DROP DATABASE IF EXISTS TUAFESTA;
CREATE DATABASE TUAFESTA CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT USAGE ON *.* TO 'TUAFESTA_USER'@'localhost';
DROP USER 'TUAFESTA_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'TUAFESTA_USER'@'localhost' IDENTIFIED BY 'TUAFESTA_USER';
GRANT ALL ON TUAFESTA.* TO TUAFESTA_USER IDENTIFIED BY 'TUAFESTA_USER';