ALTER TABLE PROFESIONAL MODIFY VIDEO1 VARCHAR(600);
ALTER TABLE PROFESIONAL MODIFY VIDEO2 VARCHAR(600);
ALTER TABLE PROFESIONAL MODIFY VIDEO3 VARCHAR(600);
ALTER TABLE PROFESIONAL MODIFY VIDEO4 VARCHAR(600);
ALTER TABLE PROFESIONAL MODIFY VIDEO5 VARCHAR(600);

ALTER TABLE PROFESIONAL_CHANGE MODIFY VIDEO1 VARCHAR(600);
ALTER TABLE PROFESIONAL_CHANGE MODIFY VIDEO2 VARCHAR(600);
ALTER TABLE PROFESIONAL_CHANGE MODIFY VIDEO3 VARCHAR(600);
ALTER TABLE PROFESIONAL_CHANGE MODIFY VIDEO4 VARCHAR(600);
ALTER TABLE PROFESIONAL_CHANGE MODIFY VIDEO5 VARCHAR(600);

COMMIT;