insert into CATEGORY (id, name, description, type, parent_id, deleted) values (1, 'Consumibles', 'Consumibles', 1, 0, 0);
	insert into CATEGORY (id, name, description, type, parent_id, deleted) values (2, 'Tortas', 'Tortas', 1, 1, 0);
		insert into CATEGORY (id, name, description, type, parent_id, deleted) values (5, 'Budin', 'Budin', 1, 2, 0);
		insert into CATEGORY (id, name, description, type, parent_id, deleted) values (6, 'Bizcochuelo', 'Bizcochuelo', 1,2, 0);
		insert into CATEGORY (id, name, description, type, parent_id, isother, deleted) values (10, 'Otros', 'Otros', 1, 2, 1, 0);
	insert into CATEGORY (id, name, description, type, parent_id, deleted) values (4, 'Tartas', 'Tartas', 1,1, 0);
		insert into CATEGORY (id, name, description, type, parent_id, deleted) values (7, 'Coco', 'Coco', 1,4, 0);
		insert into CATEGORY (id, name, description, type, parent_id, deleted) values (8, 'Pasta Frola', 'Pasta Frola', 1,4, 0);
		insert into CATEGORY (id, name, description, type, parent_id, isother, deleted) values (11, 'Otros', 'Otros', 1,4, 1, 0);
	insert into CATEGORY (id, name, description, type, parent_id, isother, deleted) values (9, 'Otros', 'Otros', 1,1, 1, 0);
insert into CATEGORY (id, name, description, type, parent_id, deleted) values (3, 'Cotillon', 'Cotillon', 1, 0, 0);
