package com.tdil.milka.dao;

import java.sql.SQLException;
import java.util.List;

import com.tdil.milka.model.MailToParent;
import com.tdil.milka.model.MailToParentExample;
import com.tdil.milka.model.valueobjects.MailToParentValueObject;

public interface MailToParentDAO {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int countMailToParentByExample(MailToParentExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int deleteMailToParentByExample(MailToParentExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int deleteMailToParentByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	Integer insertMailToParent(MailToParent record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	Integer insertMailToParentSelective(MailToParent record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	List<MailToParent> selectMailToParentByExample(MailToParentExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	MailToParent selectMailToParentByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int updateMailToParentByExampleSelective(MailToParent record, MailToParentExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int updateMailToParentByExample(MailToParent record, MailToParentExample example) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int updateMailToParentByPrimaryKeySelective(MailToParent record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAIL_TO_PARENT
	 * @mbggenerated  Mon May 28 18:13:06 ART 2012
	 */
	int updateMailToParentByPrimaryKey(MailToParent record) throws SQLException;

	List<MailToParentValueObject> selectMailToParentToApproveWithAuthor() throws SQLException;

	List<MailToParentValueObject> selectMailToParentToReviewWithAuthor() throws SQLException;
}