if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ALARM_CONF')
    drop table ALARM_CONF;

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'LIGHT_CONF')
    drop table LIGHT_CONF;

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ASYNC_JOB')
    drop table ASYNC_JOB;

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'WEBSITEUSER')
    drop table WEBSITEUSER;

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'SYSPROPERTIES')
    drop table SYSPROPERTIES;	

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'BLOB_DATA')
    drop table BLOB_DATA;
	
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'CACHE_REGION')
    drop table CACHE_REGION;
	
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'POI')
    drop table POI;

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'VERSION')
    drop table VERSION;
    
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'SYSTEMUSER')
    drop table SYSTEMUSER;

CREATE TABLE WEBSITEUSER (
  id INT NOT NULL IDENTITY ,
  lojackUserId VARCHAR(50) NULL ,
  homeUserId VARCHAR(100) NULL ,
  petUserId VARCHAR(100) NULL ,
  preventUserId VARCHAR(100) NULL ,
  id_avatar INT NULL,
  ext_avatar VARCHAR(10) NULL ,
  PRIMARY KEY (id),
  UNIQUE (lojackUserId ASC));
  
CREATE INDEX IX_WEBSITEUSER_01 ON WEBSITEUSER (homeUserId);
CREATE INDEX IX_WEBSITEUSER_02 ON WEBSITEUSER (petUserId);
CREATE INDEX IX_WEBSITEUSER_03 ON WEBSITEUSER (preventUserId);
  
CREATE TABLE ALARM_CONF (
  id INT NOT NULL IDENTITY ,
  idEntidad INT NOT NULL ,
  idWebsiteUser INT NOT NULL 
    CONSTRAINT FK_ALARM_CONF_00 FOREIGN KEY REFERENCES WEBSITEUSER(id),
  description VARCHAR(100) NULL ,
  emailNotification INT NOT NULL ,
  PRIMARY KEY (id));
    
CREATE INDEX IX_ALARM_CONF_00 ON ALARM_CONF (idWebsiteUser);

CREATE TABLE LIGHT_CONF (
  id INT NOT NULL IDENTITY ,
  idEntidad INT NOT NULL ,
  idLuz INT NOT NULL ,
  idWebsiteUser INT NOT NULL 
    CONSTRAINT FK_LIGHT_CONF_00 FOREIGN KEY REFERENCES WEBSITEUSER(id),
  description VARCHAR(100) NULL ,
  emailNotification INT NOT NULL ,
  PRIMARY KEY (id));
    
CREATE INDEX IX_LIGHT_CONF_00 ON LIGHT_CONF (idWebsiteUser);

CREATE TABLE ASYNC_JOB (
  id INT NOT NULL IDENTITY ,
  idJob INT NOT NULL ,
  idWebsiteUser INT NOT NULL 
     CONSTRAINT FK_ASYNC_JOB_00 FOREIGN KEY REFERENCES WEBSITEUSER(id),
  postDate DATETIME NOT NULL ,
  action INT NOT NULL ,
  idEntidad INT NOT NULL ,
  idLuz INT NOT NULL ,
  status INT NOT NULL ,
  PRIMARY KEY (id));

CREATE UNIQUE INDEX IX_ASYNC_JOB_00 ON ASYNC_JOB (idJob);

CREATE TABLE SYSPROPERTIES (
  id INT NOT NULL IDENTITY ,
  propKey VARCHAR(100) NOT NULL ,
  propValue VARCHAR(255) NULL ,
  description VARCHAR(300) NOT NULL ,
  deleted INT NOT NULL ,
  PRIMARY KEY (id));
  
CREATE UNIQUE INDEX UQ_SYSPROPERTIES_00 ON SYSPROPERTIES (propKey);

CREATE TABLE BLOB_DATA (
  id INT NOT NULL IDENTITY ,
  dataType VARCHAR(20) NOT NULL ,
  filename VARCHAR(100) NOT NULL ,
  content varBinary(MAX) NOT NULL ,
  deleted INT NOT NULL ,
  PRIMARY KEY (id));
  
CREATE TABLE VERSION (
	versionNumber INT NOT NULL);

INSERT INTO VERSION (versionNumber) VALUES(0);

CREATE TABLE CACHE_REGION (
  id INT NOT NULL IDENTITY ,
  version INT NOT NULL,
  name VARCHAR(200) NOT NULL ,
  deleted INT NOT NULL ,
  PRIMARY KEY (id));

CREATE UNIQUE INDEX IX_CACHE_REGION_00 ON CACHE_REGION (name);

CREATE TABLE POI (
  id INT NOT NULL IDENTITY ,
  type INT NOT NULL,
  subtype INT NOT NULL,
  name VARCHAR(200) NOT NULL ,
  description VARCHAR(4000) NOT NULL ,
  lat DECIMAL (10,8) NOT NULL ,
  lon DECIMAL (10,8) NOT  NULL ,
  PRIMARY KEY (id));

CREATE INDEX IX_POI_00 ON POI (type);

CREATE TABLE SYSTEMUSER (
  id INT NOT NULL IDENTITY ,
  username VARCHAR(20) NULL ,
  password VARCHAR(50) NULL ,
  loggingAccess INT NULL,
  syspropAccess INT NULL,
  deleted INT NOT NULL ,
  PRIMARY KEY (id));
  
CREATE INDEX IX_SYSTEMUSER_00 ON SYSTEMUSER (username);
