DROP TABLE IF EXISTS CAMERA_CONF;
CREATE TABLE CAMERA_CONF (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `url` VARCHAR(200) NOT NULL ,
  `idWebsiteUser` INT NOT NULL ,
  `description` VARCHAR(100) NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_CAMERA_CONF_00` (`idWebsiteUser` ASC),
  CONSTRAINT `FK_CAMERA_CONF_00`
    FOREIGN KEY (`idWebsiteUser` )
    REFERENCES WEBSITEUSER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;