DROP TABLE IF EXISTS VLU_DATA;
DROP TABLE IF EXISTS VLU_IMPORT_ERROR;
DROP TABLE IF EXISTS VLU_IMPORT;

CREATE TABLE VLU_IMPORT (
  id INT NOT NULL AUTO_INCREMENT ,
  filename VARCHAR(400) NOT NULL ,
  status VARCHAR(20) NOT NULL ,
  processed INT NOT NULL,
  errors INT NOT NULL,
  startTime DATETIME NULL ,
  endTime DATETIME NULL ,
  PRIMARY KEY (id))
  ENGINE = InnoDB;

CREATE TABLE VLU_IMPORT_ERROR (
  id INT NOT NULL AUTO_INCREMENT ,
  rowNumber INT NOT NULL,
  errorMessage VARCHAR(400) NULL ,
  idVluImport INT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_VLU_IMPORT_ERROR_00 FOREIGN KEY (idVluImport) REFERENCES VLU_IMPORT(id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  INDEX IX_VLU_IMPORT_ERROR_00 (idVluImport ASC))
 ENGINE = InnoDB;
  
CREATE TABLE VLU_DATA (
  id INT NOT NULL AUTO_INCREMENT ,
  dni VARCHAR(25) NOT NULL ,
  domain VARCHAR(25) NOT NULL,
  message VARCHAR(400) NULL ,
  idVluImport INT NOT NULL, 
  PRIMARY KEY (id),
  CONSTRAINT FK_VLU_DATA_00 FOREIGN KEY (idVluImport) REFERENCES VLU_IMPORT(id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  INDEX IX_VLU_DATA_00 (dni ASC),
  INDEX IX_VLU_DATA_01 (idVluImport ASC, dni ASC),
  INDEX IX_VLU_DATA_02 (idVluImport ASC))
  ENGINE = InnoDB;
  
DELETE FROM SYSPROPERTIES WHERE propKey = 'vlu.import.range';
commit;

INSERT INTO SYSPROPERTIES (propKey,propValue,description,deleted) VALUES('vlu.import.range','04:00-05:00','Rango de importacion de VLU (HH24:MM-HH24:MM)',0);

commit;