limpiar base de tua festa
DELETE FROM ADVERTISEMENT;
DELETE FROM BLOB_DATA;
DELETE FROM CLIENT;
DELETE FROM HIGHLIGHTED_CAT;
DELETE FROM PROFESIONAL;
DELETE FROM PROFESIONAL_AGENDA;
DELETE FROM PROFESIONAL_CHANGE;
DELETE FROM PROMOTION;
DELETE FROM PROMOTION_PHOTO;
DELETE FROM PROMOTION_SELL;
DELETE FROM SELL;
DELETE FROM SELL_MEDIA;
DELETE FROM SERVICE_AREA;
DELETE FROM STATISTIC;
DELETE FROM WALL;
DELETE FROM WALL_WRITTING;
DELETE FROM RAW_INSERT;
COMMIT;