package com.tdil.djmag.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tdil.djmag.dao.ImageInGalleryDAO;
import com.tdil.djmag.model.ImageInGallery;
import com.tdil.djmag.model.ImageInGalleryExample;
import java.sql.SQLException;
import java.util.List;

public class ImageInGalleryDAOImpl implements ImageInGalleryDAO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public ImageInGalleryDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int countImageInGalleryByExample(ImageInGalleryExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("IMAGE_IN_GAL.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int deleteImageInGalleryByExample(ImageInGalleryExample example) throws SQLException {
		int rows = sqlMapClient.delete("IMAGE_IN_GAL.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int deleteImageInGalleryByPrimaryKey(Integer id) throws SQLException {
		ImageInGallery _key = new ImageInGallery();
		_key.setId(id);
		int rows = sqlMapClient.delete("IMAGE_IN_GAL.deleteByPrimaryKey", _key);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public Integer insertImageInGallery(ImageInGallery record) throws SQLException {
		Object newKey = sqlMapClient.insert("IMAGE_IN_GAL.insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public Integer insertImageInGallerySelective(ImageInGallery record) throws SQLException {
		Object newKey = sqlMapClient.insert("IMAGE_IN_GAL.insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	@SuppressWarnings("unchecked")
	public List<ImageInGallery> selectImageInGalleryByExample(ImageInGalleryExample example) throws SQLException {
		List<ImageInGallery> list = sqlMapClient.queryForList("IMAGE_IN_GAL.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public ImageInGallery selectImageInGalleryByPrimaryKey(Integer id) throws SQLException {
		ImageInGallery _key = new ImageInGallery();
		_key.setId(id);
		ImageInGallery record = (ImageInGallery) sqlMapClient.queryForObject("IMAGE_IN_GAL.selectByPrimaryKey", _key);
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int updateImageInGalleryByExampleSelective(ImageInGallery record, ImageInGalleryExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("IMAGE_IN_GAL.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int updateImageInGalleryByExample(ImageInGallery record, ImageInGalleryExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("IMAGE_IN_GAL.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int updateImageInGalleryByPrimaryKeySelective(ImageInGallery record) throws SQLException {
		int rows = sqlMapClient.update("IMAGE_IN_GAL.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	public int updateImageInGalleryByPrimaryKey(ImageInGallery record) throws SQLException {
		int rows = sqlMapClient.update("IMAGE_IN_GAL.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table IMAGE_IN_GAL
	 * @mbggenerated  Tue Jun 19 18:08:48 ART 2012
	 */
	protected static class UpdateByExampleParms extends ImageInGalleryExample {
		private Object record;

		public UpdateByExampleParms(Object record, ImageInGalleryExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}