DROP DATABASE IF EXISTS LOJACK;
CREATE DATABASE LOJACK CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT USAGE ON *.* TO 'LOJACK_USER'@'localhost';
DROP USER 'LOJACK_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'LOJACK_USER'@'localhost' IDENTIFIED BY 'LOJACK_USER';
GRANT ALL ON LOJACK.* TO LOJACK_USER IDENTIFIED BY 'LOJACK_USER';