DROP DATABASE IF EXISTS PEUGEOTSVC;
CREATE DATABASE PEUGEOTSVC CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT USAGE ON *.* TO 'PEUGEOTSVC_USER'@'localhost';
DROP USER 'PEUGEOTSVC_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'PEUGEOTSVC_USER'@'localhost' IDENTIFIED BY 'PEUGEOTSVC_USER';
GRANT ALL ON PEUGEOTSVC.* TO PEUGEOTSVC_USER IDENTIFIED BY 'PEUGEOTSVC_USER';