DROP TABLE IF EXISTS ALARM_CONF;
DROP TABLE IF EXISTS LIGHT_CONF;
DROP TABLE IF EXISTS WEBSITEUSER;
DROP TABLE IF EXISTS ASYNC_JOB;
DROP TABLE IF EXISTS SYSPROPERTIES;
DROP TABLE IF EXISTS BLOB_DATA;
DROP TABLE IF EXISTS CACHE_REGION;

DROP TABLE IF EXISTS POI;

DROP TABLE IF EXISTS VERSION;

DROP TABLE IF EXISTS CAMERA_CONF;

DROP TABLE IF EXISTS SYSTEMUSER;

CREATE TABLE WEBSITEUSER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `lojackUserId` VARCHAR(50) NULL ,
  `homeUserId` VARCHAR(100) NULL ,
  `petUserId` VARCHAR(100) NULL ,
  `preventUserId` VARCHAR(100) NULL ,
  `id_avatar` INT NULL,
  `ext_avatar` VARCHAR(10) NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_WEBSITEUSER_00` (`lojackUserId` ASC),
  INDEX `IX_WEBSITEUSER_01` (`homeUserId` ASC),
  INDEX `IX_WEBSITEUSER_02` (`petUserId` ASC),
  INDEX `IX_WEBSITEUSER_03` (`preventUserId` ASC))
ENGINE = InnoDB;

CREATE TABLE ALARM_CONF (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `idEntidad` INT NOT NULL ,
  `idWebsiteUser` INT NOT NULL ,
  `description` VARCHAR(100) NULL ,
  `emailNotification` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_ALARM_CONF_00` (`idWebsiteUser` ASC),
  CONSTRAINT `FK_ALARM_CONF_00`
    FOREIGN KEY (`idWebsiteUser` )
    REFERENCES WEBSITEUSER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE LIGHT_CONF (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `idEntidad` INT NOT NULL ,
  `idLuz` INT NOT NULL ,
  `idWebsiteUser` INT NOT NULL ,
  `description` VARCHAR(100) NULL ,
  `emailNotification` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_LIGHT_CONF_00` (`idWebsiteUser` ASC),
  CONSTRAINT `FK_LIGHT_CONF_00`
    FOREIGN KEY (`idWebsiteUser` )
    REFERENCES WEBSITEUSER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE ASYNC_JOB (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `idJob` INT NOT NULL ,
  `idWebsiteUser` INT NOT NULL ,
  `postDate` DATETIME NOT NULL ,
  `action` INT NOT NULL ,
  `idEntidad` INT NOT NULL ,
  `idLuz` INT NOT NULL ,
  `status` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_ASYNC_JOB_00` (`idJob` ASC),
  CONSTRAINT `FK_ASYNC_JOB_00`
    FOREIGN KEY (`idWebsiteUser` )
    REFERENCES WEBSITEUSER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE SYSPROPERTIES (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `propKey` VARCHAR(100) NOT NULL ,
  `propValue` VARCHAR(255) NULL ,
  `description` VARCHAR(300) NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_SYSPROPERTIES_00` (`propKey` ASC))
ENGINE = InnoDB;

CREATE TABLE BLOB_DATA (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `dataType` VARCHAR(20) NOT NULL ,
  `filename` VARCHAR(100) NOT NULL ,
  `content` MEDIUMBLOB NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE VERSION (
	versionNumber INT NOT NULL)
ENGINE = MYISAM;

INSERT INTO VERSION (versionNumber) VALUES(0);

COMMIT;

CREATE TABLE CACHE_REGION (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `version` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_CACHE_REGION_00` (`name` ASC))
ENGINE = InnoDB;

CREATE TABLE POI (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `type` INT NOT NULL,
  `subtype` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL ,
  `description` VARCHAR(4000) NOT NULL ,
  `lat` DECIMAL (10,8) NOT NULL ,
  `lon` DECIMAL (10,8) NOT  NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_POI_00` (`type` ASC))
ENGINE = InnoDB;

INSERT INTO CACHE_REGION(version, name, deleted) VALUES(1, 'com.tdil.ljpeugeot.model.Category',0);
COMMIT;

CREATE TABLE SYSTEMUSER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `username` VARCHAR(20) NULL ,
  `password` VARCHAR(50) NULL ,
  `loggingAccess` INT NOT NULL,
  `syspropAccess` INT NOT NULL,
  `deleted` INT NOT NULL,
  PRIMARY KEY (`id`) ,
  INDEX `IX_SYSTEMUSER_00` (`username` ASC))
ENGINE = InnoDB;

INSERT INTO SYSTEMUSER(username,password,loggingAccess,syspropAccess, deleted) VALUES('tdil','f5314a8a0b0a34239a8bf78104f2ff4754a7a890', 1, 1, 0);
COMMIT;

CREATE TABLE CAMERA_CONF (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `url` VARCHAR(200) NOT NULL ,
  `idWebsiteUser` INT NOT NULL ,
  `description` VARCHAR(100) NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_CAMERA_CONF_00` (`idWebsiteUser` ASC),
  CONSTRAINT `FK_CAMERA_CONF_00`
    FOREIGN KEY (`idWebsiteUser` )
    REFERENCES WEBSITEUSER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
