if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'VLU_DATA')
    drop table VLU_DATA;
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'VLU_IMPORT_ERROR')
    drop table VLU_IMPORT_ERROR;
if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'VLU_IMPORT')
    drop table VLU_IMPORT;

CREATE TABLE VLU_IMPORT (
  id INT NOT NULL IDENTITY ,
  filename VARCHAR(400) NOT NULL ,
  status VARCHAR(20) NOT NULL ,
  processed INT NOT NULL,
  errors INT NOT NULL,
  startTime DATETIME NULL ,
  endTime DATETIME NULL ,
  PRIMARY KEY (id));

CREATE TABLE VLU_IMPORT_ERROR (
  id INT NOT NULL IDENTITY ,
  rowNumber INT NOT NULL,
  errorMessage VARCHAR(400) NULL ,
  idVluImport INT NOT NULL 
    CONSTRAINT FK_VLU_IMPORT_ERROR_00 FOREIGN KEY REFERENCES VLU_IMPORT(id),
  PRIMARY KEY (id));
  
  CREATE INDEX IX_VLU_IMPORT_ERROR_00 ON VLU_IMPORT_ERROR (idVluImport);

CREATE TABLE VLU_DATA (
  id INT NOT NULL IDENTITY ,
  dni VARCHAR(25) NOT NULL ,
  domain VARCHAR(25) NOT NULL,
  message VARCHAR(400) NULL ,
  idVluImport INT NOT NULL 
    CONSTRAINT FK_VLU_DATA_00 FOREIGN KEY REFERENCES VLU_IMPORT(id),
  PRIMARY KEY (id));
    
CREATE INDEX IX_VLU_DATA_00 ON VLU_DATA (dni);
CREATE INDEX IX_VLU_DATA_01 ON VLU_DATA (idVluImport, dni);
CREATE INDEX IX_VLU_DATA_02 ON VLU_DATA (idVluImport);

DELETE FROM SYSPROPERTIES WHERE propKey = 'vlu.import.range';
commit;

INSERT INTO SYSPROPERTIES (propKey,propValue,description,deleted) VALUES('vlu.import.range','04:00-05:00','Rango de importacion de VLU (HH24:MM-HH24:MM)',0);

commit;