package com.tdil.milka.model;

import com.tdil.ibatis.PersistentObject;
import java.util.Date;

public class MailToParent extends PersistentObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.creationDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Date creationdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.publishDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Date publishdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.id_author
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer idAuthor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.title
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.description
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.frontCover
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer frontcover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.showInHome
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer showinhome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.approved
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer approved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.id_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer idBlobData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.ext_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String extBlobData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.id_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer idApprovedData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.ext_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String extApprovedData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.id_click_counter
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private Integer idClickCounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.url_link
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String urlLink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAIL_TO_PARENT.url_target
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	private String urlTarget;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.creationDate
	 * @return  the value of MAIL_TO_PARENT.creationDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Date getCreationdate() {
		return creationdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.creationDate
	 * @param creationdate  the value for MAIL_TO_PARENT.creationDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.publishDate
	 * @return  the value of MAIL_TO_PARENT.publishDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Date getPublishdate() {
		return publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.publishDate
	 * @param publishdate  the value for MAIL_TO_PARENT.publishDate
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.id_author
	 * @return  the value of MAIL_TO_PARENT.id_author
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getIdAuthor() {
		return idAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.id_author
	 * @param idAuthor  the value for MAIL_TO_PARENT.id_author
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setIdAuthor(Integer idAuthor) {
		this.idAuthor = idAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.title
	 * @return  the value of MAIL_TO_PARENT.title
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.title
	 * @param title  the value for MAIL_TO_PARENT.title
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.description
	 * @return  the value of MAIL_TO_PARENT.description
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.description
	 * @param description  the value for MAIL_TO_PARENT.description
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.frontCover
	 * @return  the value of MAIL_TO_PARENT.frontCover
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getFrontcover() {
		return frontcover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.frontCover
	 * @param frontcover  the value for MAIL_TO_PARENT.frontCover
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setFrontcover(Integer frontcover) {
		this.frontcover = frontcover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.showInHome
	 * @return  the value of MAIL_TO_PARENT.showInHome
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getShowinhome() {
		return showinhome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.showInHome
	 * @param showinhome  the value for MAIL_TO_PARENT.showInHome
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setShowinhome(Integer showinhome) {
		this.showinhome = showinhome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.approved
	 * @return  the value of MAIL_TO_PARENT.approved
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getApproved() {
		return approved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.approved
	 * @param approved  the value for MAIL_TO_PARENT.approved
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setApproved(Integer approved) {
		this.approved = approved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.id_blob_data
	 * @return  the value of MAIL_TO_PARENT.id_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getIdBlobData() {
		return idBlobData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.id_blob_data
	 * @param idBlobData  the value for MAIL_TO_PARENT.id_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setIdBlobData(Integer idBlobData) {
		this.idBlobData = idBlobData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.ext_blob_data
	 * @return  the value of MAIL_TO_PARENT.ext_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getExtBlobData() {
		return extBlobData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.ext_blob_data
	 * @param extBlobData  the value for MAIL_TO_PARENT.ext_blob_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setExtBlobData(String extBlobData) {
		this.extBlobData = extBlobData == null ? null : extBlobData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.id_approved_data
	 * @return  the value of MAIL_TO_PARENT.id_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getIdApprovedData() {
		return idApprovedData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.id_approved_data
	 * @param idApprovedData  the value for MAIL_TO_PARENT.id_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setIdApprovedData(Integer idApprovedData) {
		this.idApprovedData = idApprovedData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.ext_approved_data
	 * @return  the value of MAIL_TO_PARENT.ext_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getExtApprovedData() {
		return extApprovedData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.ext_approved_data
	 * @param extApprovedData  the value for MAIL_TO_PARENT.ext_approved_data
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setExtApprovedData(String extApprovedData) {
		this.extApprovedData = extApprovedData == null ? null : extApprovedData.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.id_click_counter
	 * @return  the value of MAIL_TO_PARENT.id_click_counter
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Integer getIdClickCounter() {
		return idClickCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.id_click_counter
	 * @param idClickCounter  the value for MAIL_TO_PARENT.id_click_counter
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setIdClickCounter(Integer idClickCounter) {
		this.idClickCounter = idClickCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.url_link
	 * @return  the value of MAIL_TO_PARENT.url_link
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getUrlLink() {
		return urlLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.url_link
	 * @param urlLink  the value for MAIL_TO_PARENT.url_link
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink == null ? null : urlLink.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MAIL_TO_PARENT.url_target
	 * @return  the value of MAIL_TO_PARENT.url_target
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getUrlTarget() {
		return urlTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MAIL_TO_PARENT.url_target
	 * @param urlTarget  the value for MAIL_TO_PARENT.url_target
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setUrlTarget(String urlTarget) {
		this.urlTarget = urlTarget == null ? null : urlTarget.trim();
	}
}