package com.tdil.milka.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PostItExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public PostItExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected PostItExample(PostItExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.distinct = example.distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table POST_IT
	 * @mbggenerated  Thu May 31 22:35:48 ART 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected GeneratedCriteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("pi.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("pi.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("pi.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("pi.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("pi.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("pi.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("pi.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("pi.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("pi.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("pi.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCreationdateIsNull() {
			addCriterion("pi.creationDate is null");
			return (Criteria) this;
		}

		public Criteria andCreationdateIsNotNull() {
			addCriterion("pi.creationDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreationdateEqualTo(Date value) {
			addCriterion("pi.creationDate =", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateNotEqualTo(Date value) {
			addCriterion("pi.creationDate <>", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateGreaterThan(Date value) {
			addCriterion("pi.creationDate >", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
			addCriterion("pi.creationDate >=", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateLessThan(Date value) {
			addCriterion("pi.creationDate <", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateLessThanOrEqualTo(Date value) {
			addCriterion("pi.creationDate <=", value, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateIn(List<Date> values) {
			addCriterion("pi.creationDate in", values, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateNotIn(List<Date> values) {
			addCriterion("pi.creationDate not in", values, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateBetween(Date value1, Date value2) {
			addCriterion("pi.creationDate between", value1, value2, "creationdate");
			return (Criteria) this;
		}

		public Criteria andCreationdateNotBetween(Date value1, Date value2) {
			addCriterion("pi.creationDate not between", value1, value2, "creationdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNull() {
			addCriterion("pi.publishDate is null");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNotNull() {
			addCriterion("pi.publishDate is not null");
			return (Criteria) this;
		}

		public Criteria andPublishdateEqualTo(Date value) {
			addCriterion("pi.publishDate =", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotEqualTo(Date value) {
			addCriterion("pi.publishDate <>", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThan(Date value) {
			addCriterion("pi.publishDate >", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThanOrEqualTo(Date value) {
			addCriterion("pi.publishDate >=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThan(Date value) {
			addCriterion("pi.publishDate <", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThanOrEqualTo(Date value) {
			addCriterion("pi.publishDate <=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateIn(List<Date> values) {
			addCriterion("pi.publishDate in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotIn(List<Date> values) {
			addCriterion("pi.publishDate not in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateBetween(Date value1, Date value2) {
			addCriterion("pi.publishDate between", value1, value2, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotBetween(Date value1, Date value2) {
			addCriterion("pi.publishDate not between", value1, value2, "publishdate");
			return (Criteria) this;
		}

		public Criteria andIdAuthorIsNull() {
			addCriterion("pi.id_author is null");
			return (Criteria) this;
		}

		public Criteria andIdAuthorIsNotNull() {
			addCriterion("pi.id_author is not null");
			return (Criteria) this;
		}

		public Criteria andIdAuthorEqualTo(Integer value) {
			addCriterion("pi.id_author =", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorNotEqualTo(Integer value) {
			addCriterion("pi.id_author <>", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorGreaterThan(Integer value) {
			addCriterion("pi.id_author >", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.id_author >=", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorLessThan(Integer value) {
			addCriterion("pi.id_author <", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorLessThanOrEqualTo(Integer value) {
			addCriterion("pi.id_author <=", value, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorIn(List<Integer> values) {
			addCriterion("pi.id_author in", values, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorNotIn(List<Integer> values) {
			addCriterion("pi.id_author not in", values, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_author between", value1, value2, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andIdAuthorNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_author not between", value1, value2, "idAuthor");
			return (Criteria) this;
		}

		public Criteria andOriginaltextIsNull() {
			addCriterion("pi.originalText is null");
			return (Criteria) this;
		}

		public Criteria andOriginaltextIsNotNull() {
			addCriterion("pi.originalText is not null");
			return (Criteria) this;
		}

		public Criteria andOriginaltextEqualTo(String value) {
			addCriterion("pi.originalText =", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextNotEqualTo(String value) {
			addCriterion("pi.originalText <>", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextGreaterThan(String value) {
			addCriterion("pi.originalText >", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextGreaterThanOrEqualTo(String value) {
			addCriterion("pi.originalText >=", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextLessThan(String value) {
			addCriterion("pi.originalText <", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextLessThanOrEqualTo(String value) {
			addCriterion("pi.originalText <=", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextLike(String value) {
			addCriterion("pi.originalText like", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextNotLike(String value) {
			addCriterion("pi.originalText not like", value, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextIn(List<String> values) {
			addCriterion("pi.originalText in", values, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextNotIn(List<String> values) {
			addCriterion("pi.originalText not in", values, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextBetween(String value1, String value2) {
			addCriterion("pi.originalText between", value1, value2, "originaltext");
			return (Criteria) this;
		}

		public Criteria andOriginaltextNotBetween(String value1, String value2) {
			addCriterion("pi.originalText not between", value1, value2, "originaltext");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("pi.title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("pi.title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("pi.title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("pi.title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("pi.title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("pi.title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("pi.title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("pi.title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("pi.title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("pi.title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("pi.title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("pi.title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("pi.title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("pi.title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("pi.description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("pi.description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("pi.description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("pi.description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("pi.description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("pi.description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("pi.description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("pi.description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("pi.description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("pi.description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("pi.description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("pi.description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("pi.description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("pi.description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andApprovedIsNull() {
			addCriterion("pi.approved is null");
			return (Criteria) this;
		}

		public Criteria andApprovedIsNotNull() {
			addCriterion("pi.approved is not null");
			return (Criteria) this;
		}

		public Criteria andApprovedEqualTo(Integer value) {
			addCriterion("pi.approved =", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotEqualTo(Integer value) {
			addCriterion("pi.approved <>", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedGreaterThan(Integer value) {
			addCriterion("pi.approved >", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.approved >=", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedLessThan(Integer value) {
			addCriterion("pi.approved <", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedLessThanOrEqualTo(Integer value) {
			addCriterion("pi.approved <=", value, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedIn(List<Integer> values) {
			addCriterion("pi.approved in", values, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotIn(List<Integer> values) {
			addCriterion("pi.approved not in", values, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedBetween(Integer value1, Integer value2) {
			addCriterion("pi.approved between", value1, value2, "approved");
			return (Criteria) this;
		}

		public Criteria andApprovedNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.approved not between", value1, value2, "approved");
			return (Criteria) this;
		}

		public Criteria andIdThumbIsNull() {
			addCriterion("pi.id_thumb is null");
			return (Criteria) this;
		}

		public Criteria andIdThumbIsNotNull() {
			addCriterion("pi.id_thumb is not null");
			return (Criteria) this;
		}

		public Criteria andIdThumbEqualTo(Integer value) {
			addCriterion("pi.id_thumb =", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbNotEqualTo(Integer value) {
			addCriterion("pi.id_thumb <>", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbGreaterThan(Integer value) {
			addCriterion("pi.id_thumb >", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.id_thumb >=", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbLessThan(Integer value) {
			addCriterion("pi.id_thumb <", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbLessThanOrEqualTo(Integer value) {
			addCriterion("pi.id_thumb <=", value, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbIn(List<Integer> values) {
			addCriterion("pi.id_thumb in", values, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbNotIn(List<Integer> values) {
			addCriterion("pi.id_thumb not in", values, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_thumb between", value1, value2, "idThumb");
			return (Criteria) this;
		}

		public Criteria andIdThumbNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_thumb not between", value1, value2, "idThumb");
			return (Criteria) this;
		}

		public Criteria andExtThumIsNull() {
			addCriterion("pi.ext_thum is null");
			return (Criteria) this;
		}

		public Criteria andExtThumIsNotNull() {
			addCriterion("pi.ext_thum is not null");
			return (Criteria) this;
		}

		public Criteria andExtThumEqualTo(String value) {
			addCriterion("pi.ext_thum =", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumNotEqualTo(String value) {
			addCriterion("pi.ext_thum <>", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumGreaterThan(String value) {
			addCriterion("pi.ext_thum >", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumGreaterThanOrEqualTo(String value) {
			addCriterion("pi.ext_thum >=", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumLessThan(String value) {
			addCriterion("pi.ext_thum <", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumLessThanOrEqualTo(String value) {
			addCriterion("pi.ext_thum <=", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumLike(String value) {
			addCriterion("pi.ext_thum like", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumNotLike(String value) {
			addCriterion("pi.ext_thum not like", value, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumIn(List<String> values) {
			addCriterion("pi.ext_thum in", values, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumNotIn(List<String> values) {
			addCriterion("pi.ext_thum not in", values, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumBetween(String value1, String value2) {
			addCriterion("pi.ext_thum between", value1, value2, "extThum");
			return (Criteria) this;
		}

		public Criteria andExtThumNotBetween(String value1, String value2) {
			addCriterion("pi.ext_thum not between", value1, value2, "extThum");
			return (Criteria) this;
		}

		public Criteria andIdImageIsNull() {
			addCriterion("pi.id_image is null");
			return (Criteria) this;
		}

		public Criteria andIdImageIsNotNull() {
			addCriterion("pi.id_image is not null");
			return (Criteria) this;
		}

		public Criteria andIdImageEqualTo(Integer value) {
			addCriterion("pi.id_image =", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageNotEqualTo(Integer value) {
			addCriterion("pi.id_image <>", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageGreaterThan(Integer value) {
			addCriterion("pi.id_image >", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.id_image >=", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageLessThan(Integer value) {
			addCriterion("pi.id_image <", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageLessThanOrEqualTo(Integer value) {
			addCriterion("pi.id_image <=", value, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageIn(List<Integer> values) {
			addCriterion("pi.id_image in", values, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageNotIn(List<Integer> values) {
			addCriterion("pi.id_image not in", values, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_image between", value1, value2, "idImage");
			return (Criteria) this;
		}

		public Criteria andIdImageNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_image not between", value1, value2, "idImage");
			return (Criteria) this;
		}

		public Criteria andExtImageIsNull() {
			addCriterion("pi.ext_image is null");
			return (Criteria) this;
		}

		public Criteria andExtImageIsNotNull() {
			addCriterion("pi.ext_image is not null");
			return (Criteria) this;
		}

		public Criteria andExtImageEqualTo(String value) {
			addCriterion("pi.ext_image =", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageNotEqualTo(String value) {
			addCriterion("pi.ext_image <>", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageGreaterThan(String value) {
			addCriterion("pi.ext_image >", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageGreaterThanOrEqualTo(String value) {
			addCriterion("pi.ext_image >=", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageLessThan(String value) {
			addCriterion("pi.ext_image <", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageLessThanOrEqualTo(String value) {
			addCriterion("pi.ext_image <=", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageLike(String value) {
			addCriterion("pi.ext_image like", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageNotLike(String value) {
			addCriterion("pi.ext_image not like", value, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageIn(List<String> values) {
			addCriterion("pi.ext_image in", values, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageNotIn(List<String> values) {
			addCriterion("pi.ext_image not in", values, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageBetween(String value1, String value2) {
			addCriterion("pi.ext_image between", value1, value2, "extImage");
			return (Criteria) this;
		}

		public Criteria andExtImageNotBetween(String value1, String value2) {
			addCriterion("pi.ext_image not between", value1, value2, "extImage");
			return (Criteria) this;
		}

		public Criteria andUrlLinkIsNull() {
			addCriterion("pi.url_link is null");
			return (Criteria) this;
		}

		public Criteria andUrlLinkIsNotNull() {
			addCriterion("pi.url_link is not null");
			return (Criteria) this;
		}

		public Criteria andUrlLinkEqualTo(String value) {
			addCriterion("pi.url_link =", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkNotEqualTo(String value) {
			addCriterion("pi.url_link <>", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkGreaterThan(String value) {
			addCriterion("pi.url_link >", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkGreaterThanOrEqualTo(String value) {
			addCriterion("pi.url_link >=", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkLessThan(String value) {
			addCriterion("pi.url_link <", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkLessThanOrEqualTo(String value) {
			addCriterion("pi.url_link <=", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkLike(String value) {
			addCriterion("pi.url_link like", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkNotLike(String value) {
			addCriterion("pi.url_link not like", value, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkIn(List<String> values) {
			addCriterion("pi.url_link in", values, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkNotIn(List<String> values) {
			addCriterion("pi.url_link not in", values, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkBetween(String value1, String value2) {
			addCriterion("pi.url_link between", value1, value2, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlLinkNotBetween(String value1, String value2) {
			addCriterion("pi.url_link not between", value1, value2, "urlLink");
			return (Criteria) this;
		}

		public Criteria andUrlTargetIsNull() {
			addCriterion("pi.url_target is null");
			return (Criteria) this;
		}

		public Criteria andUrlTargetIsNotNull() {
			addCriterion("pi.url_target is not null");
			return (Criteria) this;
		}

		public Criteria andUrlTargetEqualTo(String value) {
			addCriterion("pi.url_target =", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetNotEqualTo(String value) {
			addCriterion("pi.url_target <>", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetGreaterThan(String value) {
			addCriterion("pi.url_target >", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetGreaterThanOrEqualTo(String value) {
			addCriterion("pi.url_target >=", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetLessThan(String value) {
			addCriterion("pi.url_target <", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetLessThanOrEqualTo(String value) {
			addCriterion("pi.url_target <=", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetLike(String value) {
			addCriterion("pi.url_target like", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetNotLike(String value) {
			addCriterion("pi.url_target not like", value, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetIn(List<String> values) {
			addCriterion("pi.url_target in", values, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetNotIn(List<String> values) {
			addCriterion("pi.url_target not in", values, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetBetween(String value1, String value2) {
			addCriterion("pi.url_target between", value1, value2, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andUrlTargetNotBetween(String value1, String value2) {
			addCriterion("pi.url_target not between", value1, value2, "urlTarget");
			return (Criteria) this;
		}

		public Criteria andPositionIsNull() {
			addCriterion("pi.position is null");
			return (Criteria) this;
		}

		public Criteria andPositionIsNotNull() {
			addCriterion("pi.position is not null");
			return (Criteria) this;
		}

		public Criteria andPositionEqualTo(Integer value) {
			addCriterion("pi.position =", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotEqualTo(Integer value) {
			addCriterion("pi.position <>", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThan(Integer value) {
			addCriterion("pi.position >", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.position >=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThan(Integer value) {
			addCriterion("pi.position <", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThanOrEqualTo(Integer value) {
			addCriterion("pi.position <=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionIn(List<Integer> values) {
			addCriterion("pi.position in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotIn(List<Integer> values) {
			addCriterion("pi.position not in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionBetween(Integer value1, Integer value2) {
			addCriterion("pi.position between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.position not between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andColorIsNull() {
			addCriterion("pi.color is null");
			return (Criteria) this;
		}

		public Criteria andColorIsNotNull() {
			addCriterion("pi.color is not null");
			return (Criteria) this;
		}

		public Criteria andColorEqualTo(String value) {
			addCriterion("pi.color =", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotEqualTo(String value) {
			addCriterion("pi.color <>", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThan(String value) {
			addCriterion("pi.color >", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThanOrEqualTo(String value) {
			addCriterion("pi.color >=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThan(String value) {
			addCriterion("pi.color <", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThanOrEqualTo(String value) {
			addCriterion("pi.color <=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLike(String value) {
			addCriterion("pi.color like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotLike(String value) {
			addCriterion("pi.color not like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorIn(List<String> values) {
			addCriterion("pi.color in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotIn(List<String> values) {
			addCriterion("pi.color not in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorBetween(String value1, String value2) {
			addCriterion("pi.color between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotBetween(String value1, String value2) {
			addCriterion("pi.color not between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterIsNull() {
			addCriterion("pi.id_click_counter is null");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterIsNotNull() {
			addCriterion("pi.id_click_counter is not null");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterEqualTo(Integer value) {
			addCriterion("pi.id_click_counter =", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterNotEqualTo(Integer value) {
			addCriterion("pi.id_click_counter <>", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterGreaterThan(Integer value) {
			addCriterion("pi.id_click_counter >", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.id_click_counter >=", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterLessThan(Integer value) {
			addCriterion("pi.id_click_counter <", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterLessThanOrEqualTo(Integer value) {
			addCriterion("pi.id_click_counter <=", value, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterIn(List<Integer> values) {
			addCriterion("pi.id_click_counter in", values, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterNotIn(List<Integer> values) {
			addCriterion("pi.id_click_counter not in", values, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_click_counter between", value1, value2, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andIdClickCounterNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.id_click_counter not between", value1, value2, "idClickCounter");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("pi.deleted is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("pi.deleted is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Integer value) {
			addCriterion("pi.deleted =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Integer value) {
			addCriterion("pi.deleted <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Integer value) {
			addCriterion("pi.deleted >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
			addCriterion("pi.deleted >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Integer value) {
			addCriterion("pi.deleted <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Integer value) {
			addCriterion("pi.deleted <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Integer> values) {
			addCriterion("pi.deleted in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Integer> values) {
			addCriterion("pi.deleted not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Integer value1, Integer value2) {
			addCriterion("pi.deleted between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
			addCriterion("pi.deleted not between", value1, value2, "deleted");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table POST_IT
     *
     * @mbggenerated do_not_delete_during_merge Sun May 06 21:14:25 ART 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}