DROP TABLE IF EXISTS SYSTEMUSER;
DROP TABLE IF EXISTS SYSPROPERTIES;
DROP TABLE IF EXISTS MENUITEM;
DROP TABLE IF EXISTS NEWSLETTER;
DROP TABLE IF EXISTS BANNER_POSITION;
DROP TABLE IF EXISTS BANNER;
DROP TABLE IF EXISTS BLOB_DATA;
DROP TABLE IF EXISTS FOOTER;
DROP TABLE IF EXISTS TWITTER_FEED;
DROP TABLE IF EXISTS FACEBOOK_FEED;
DROP TABLE IF EXISTS VIDEO;
DROP TABLE IF EXISTS RANKING_NOTE;
DROP TABLE IF EXISTS RANKING_NOTE_COUNTRY;
DROP TABLE IF EXISTS NOTE_IMAGE;
DROP TABLE IF EXISTS NOTE_COUNTRY;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS MAGAZINE;

CREATE  TABLE SYSTEMUSER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `username` VARCHAR(20) NULL ,
  `password` VARCHAR(4000) NULL ,
  `name` VARCHAR(255) NULL ,
  `email` VARCHAR(150) NULL ,
  `resetcode` VARCHAR(100) NULL ,
  `deleted` INT NOT NULL,
  PRIMARY KEY (`id`) ,
  INDEX `IX_SYSTEMUSER_00` (`username` ASC),
  INDEX `IX_SYSTEMUSER_01` (`email` ASC))
ENGINE = InnoDB;

CREATE  TABLE SYSPROPERTIES (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `propKey` VARCHAR(100) NOT NULL ,
  `propValue` VARCHAR(255) NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_SYSPROPERTIES_00` (`propKey` ASC))
ENGINE = InnoDB;

CREATE TABLE BLOB_DATA (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `dataType` VARCHAR(20) NOT NULL ,
  `filename` VARCHAR(100) NOT NULL ,
  `content` MEDIUMBLOB NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE COUNTRY (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(250) NOT NULL ,
  `iso_code_2` VARCHAR(2) NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_COUNTRY_00` (`name` ASC))
ENGINE = InnoDB;

CREATE TABLE SECTION (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(250) NOT NULL ,
  `sectionType` VARCHAR(100) NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_SECTION_00` (`name` ASC))
ENGINE = InnoDB;

CREATE TABLE MENUITEM (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_country` INT NOT NULL,
  `id_section` INT NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `position` INT NOT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_MENUITEM_00` (`id_country` ASC, `id_section` ASC) ,
  CONSTRAINT `FK_MENUITEM_00`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MENUITEM_01`
    FOREIGN KEY (`id_section` )
    REFERENCES SECTION (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE NEWSLETTER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(100) NOT NULL ,
  `subscriptiondate` DATE NOT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE RANKING_NOTE (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `description` VARCHAR(250) NOT NULL ,
  `positions` TEXT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE RANKING_NOTE_COUNTRY (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_ranking_note` INT NOT NULL,
  `id_country` INT NOT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_RANKING_NOTE_COUNTRY_00` (`id_ranking_note` ASC),
  UNIQUE INDEX `UQ_RANKING_NOTE_COUNTRY_00` (`id_country` ASC),
  CONSTRAINT `FK_RANKING_NOTE_COUNTRY_01`
    FOREIGN KEY (`id_ranking_note` )
    REFERENCES RANKING_NOTE (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RANKING_NOTE_COUNTRY_02`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE NOTE (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `title` VARCHAR(250) NOT NULL ,
  `summary` VARCHAR(4000) NULL ,
  `content` MEDIUMTEXT NOT NULL ,
  `id_section` INT NOT NULL,
  `web_title` VARCHAR(250) NOT NULL ,
  `from_date` DATE NOT NULL ,
  `to_date` DATE NULL ,
  `frontCover` INT NOT NULL ,
  `popular` INT NOT NULL ,
  `showInAgenda` INT NOT NULL ,
  `agenda_date` DATE NULL ,
  `frontCoverExt` VARCHAR(10) NULL ,
  `frontCover_id` INT NULL,
  `agendaExt` VARCHAR(10) NULL ,
  `agenda_id` INT NULL,
  `lastNewsCoverExt` VARCHAR(10) NULL ,
  `lastNewsCover_id` INT NULL,
  `lastNewsThumbExt` VARCHAR(10) NULL ,
  `lastNewsThumb_id` INT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_NOTE_01`
    FOREIGN KEY (`id_section` )
    REFERENCES SECTION (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE NOTE_COUNTRY (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_note` INT NOT NULL,
  `id_country` INT NOT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_NOTE_COUNTRY_00` (`id_note` ASC),
  CONSTRAINT `FK_NOTE_COUNTRY_01`
    FOREIGN KEY (`id_note` )
    REFERENCES NOTE (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NOTE_COUNTRY_02`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE NOTE_IMAGE (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_note` INT NOT NULL,
  `title` VARCHAR(250) NULL ,
  `summary` VARCHAR(4000) NULL ,
  `content` MEDIUMTEXT NULL ,
  `fileName` VARCHAR(100) NOT NULL ,
  `extension` VARCHAR(10) NULL ,
  `contentType` VARCHAR(100) NULL ,
  `noteImage` MEDIUMBLOB NULL ,
  `orderNumber` INT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `IX_NOTE_COUNTRY_00` (`id_note` ASC),
  CONSTRAINT `FK_NOTE_IMAGE_01`
    FOREIGN KEY (`id_note` )
    REFERENCES NOTE (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE BANNER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `description` VARCHAR(250) NOT NULL ,
  `htmlContent` TEXT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE TWITTER_FEED (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_country` INT NOT NULL,
  `htmlContent` TEXT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_TWITTER_FEED_00` (`id_country` ASC),
  CONSTRAINT `FK_TWITTER_FEED_00`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE FACEBOOK_FEED (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_country` INT NOT NULL,
  `htmlContent` TEXT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_FACEBOOK_FEED_00` (`id_country` ASC),
  CONSTRAINT `FK_FACEBOOK_FEED_00`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE MAGAZINE (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `description` VARCHAR(4000) NOT NULL ,
  `publish_date` DATE NOT NULL ,
  `frontCoverExt` VARCHAR(10) NOT NULL ,
  `frontCover_id` INT NULL,
  `magazineContentExt` VARCHAR(10) NULL ,
  `magazineContent_id` INT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE VIDEO (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `title` VARCHAR(250) NOT NULL ,
  `description` VARCHAR(4000) NOT NULL ,
  `id_country` INT NOT NULL,
  `htmlContent` TEXT NOT NULL ,
  `frontCover` INT NOT NULL ,
  `popular` INT NOT NULL ,
  `frontCoverExt` VARCHAR(10) NOT NULL ,
  `frontCover_id` INT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `UQ_VIDEO_00` (`id_country` ASC),
  CONSTRAINT `FK_VIDEO_00`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE BANNER_POSITION (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_country` INT NOT NULL,
  `id_banner` INT NOT NULL,
  `position` VARCHAR(100) NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_BANNER_POSITION_00` (`id_country` ASC, `position` asc),
  CONSTRAINT `FK_BANNER_POSITION_00`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BANNER_POSITION_01`
    FOREIGN KEY (`id_banner` )
    REFERENCES BANNER (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE FOOTER (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `id_country` INT NOT NULL,
  `htmlContent` TEXT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_FOOTER_00` (`id_country` ASC),
  CONSTRAINT `FK_FOOTER_01`
    FOREIGN KEY (`id_country` )
    REFERENCES COUNTRY (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO SYSTEMUSER(username,password,name,email, deleted) VALUES('Admin',SHA1('Admin'), 'Admin', 'admin@admin.com', 0);
INSERT INTO SECTION (name, sectionType, deleted) VALUES('RANKING_100','RANKING_100', 0);
INSERT INTO SECTION (name, sectionType, deleted) VALUES('VIDEOS','VIDEOS', 0);