DROP DATABASE IF EXISTS MILKACORAZONES;
CREATE DATABASE MILKACORAZONES CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT USAGE ON *.* TO 'MILKACOR_USER'@'localhost';
DROP USER 'MILKACOR_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'MILKACOR_USER'@'localhost' IDENTIFIED BY 'MILKACOR_USER';
GRANT ALL ON MILKACORAZONES.* TO MILKACOR_USER IDENTIFIED BY 'MILKACOR_USER';