package com.tdil.tuafesta.model;

import com.tdil.ibatis.PersistentObject;
import java.util.Date;

public class Profesional extends PersistentObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.id_profesional_change
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer idProfesionalChange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.reviewDate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Date reviewdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.disapproveReason
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String disapprovereason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.id_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer idProfilePicture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.ext_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String extProfilePicture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.firstname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.lastname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.sex
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.birthdate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Date birthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.phoneAreaCode
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String phoneareacode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.phoneNumber
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String phonenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.phoneExtension
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String phoneextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.phoneType
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String phonetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.id_geolevel
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer idGeolevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.businessName
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String businessname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.cuit
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String cuit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.iibb
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String iibb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.email
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.password
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.website
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.facebookid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String facebookid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.facebook
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String facebook;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.businesshours
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String businesshours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.description
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.video1
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String video1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.video2
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String video2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.video3
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String video3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.video4
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String video4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.video5
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String video5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.emailvalid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer emailvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.status
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.datachanged
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer datachanged;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.id_wall
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private Integer idWall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROFESIONAL.verifemail
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	private String verifemail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.id_profesional_change
	 * @return  the value of PROFESIONAL.id_profesional_change
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getIdProfesionalChange() {
		return idProfesionalChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.id_profesional_change
	 * @param idProfesionalChange  the value for PROFESIONAL.id_profesional_change
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setIdProfesionalChange(Integer idProfesionalChange) {
		this.idProfesionalChange = idProfesionalChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.reviewDate
	 * @return  the value of PROFESIONAL.reviewDate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Date getReviewdate() {
		return reviewdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.reviewDate
	 * @param reviewdate  the value for PROFESIONAL.reviewDate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setReviewdate(Date reviewdate) {
		this.reviewdate = reviewdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.disapproveReason
	 * @return  the value of PROFESIONAL.disapproveReason
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getDisapprovereason() {
		return disapprovereason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.disapproveReason
	 * @param disapprovereason  the value for PROFESIONAL.disapproveReason
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setDisapprovereason(String disapprovereason) {
		this.disapprovereason = disapprovereason == null ? null : disapprovereason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.id_profile_picture
	 * @return  the value of PROFESIONAL.id_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getIdProfilePicture() {
		return idProfilePicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.id_profile_picture
	 * @param idProfilePicture  the value for PROFESIONAL.id_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setIdProfilePicture(Integer idProfilePicture) {
		this.idProfilePicture = idProfilePicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.ext_profile_picture
	 * @return  the value of PROFESIONAL.ext_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getExtProfilePicture() {
		return extProfilePicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.ext_profile_picture
	 * @param extProfilePicture  the value for PROFESIONAL.ext_profile_picture
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setExtProfilePicture(String extProfilePicture) {
		this.extProfilePicture = extProfilePicture == null ? null : extProfilePicture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.firstname
	 * @return  the value of PROFESIONAL.firstname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.firstname
	 * @param firstname  the value for PROFESIONAL.firstname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname == null ? null : firstname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.lastname
	 * @return  the value of PROFESIONAL.lastname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.lastname
	 * @param lastname  the value for PROFESIONAL.lastname
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname == null ? null : lastname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.sex
	 * @return  the value of PROFESIONAL.sex
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.sex
	 * @param sex  the value for PROFESIONAL.sex
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.birthdate
	 * @return  the value of PROFESIONAL.birthdate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Date getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.birthdate
	 * @param birthdate  the value for PROFESIONAL.birthdate
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.phoneAreaCode
	 * @return  the value of PROFESIONAL.phoneAreaCode
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getPhoneareacode() {
		return phoneareacode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.phoneAreaCode
	 * @param phoneareacode  the value for PROFESIONAL.phoneAreaCode
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setPhoneareacode(String phoneareacode) {
		this.phoneareacode = phoneareacode == null ? null : phoneareacode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.phoneNumber
	 * @return  the value of PROFESIONAL.phoneNumber
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.phoneNumber
	 * @param phonenumber  the value for PROFESIONAL.phoneNumber
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber == null ? null : phonenumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.phoneExtension
	 * @return  the value of PROFESIONAL.phoneExtension
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getPhoneextension() {
		return phoneextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.phoneExtension
	 * @param phoneextension  the value for PROFESIONAL.phoneExtension
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setPhoneextension(String phoneextension) {
		this.phoneextension = phoneextension == null ? null : phoneextension.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.phoneType
	 * @return  the value of PROFESIONAL.phoneType
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getPhonetype() {
		return phonetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.phoneType
	 * @param phonetype  the value for PROFESIONAL.phoneType
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setPhonetype(String phonetype) {
		this.phonetype = phonetype == null ? null : phonetype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.id_geolevel
	 * @return  the value of PROFESIONAL.id_geolevel
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getIdGeolevel() {
		return idGeolevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.id_geolevel
	 * @param idGeolevel  the value for PROFESIONAL.id_geolevel
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setIdGeolevel(Integer idGeolevel) {
		this.idGeolevel = idGeolevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.businessName
	 * @return  the value of PROFESIONAL.businessName
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getBusinessname() {
		return businessname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.businessName
	 * @param businessname  the value for PROFESIONAL.businessName
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setBusinessname(String businessname) {
		this.businessname = businessname == null ? null : businessname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.cuit
	 * @return  the value of PROFESIONAL.cuit
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getCuit() {
		return cuit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.cuit
	 * @param cuit  the value for PROFESIONAL.cuit
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setCuit(String cuit) {
		this.cuit = cuit == null ? null : cuit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.iibb
	 * @return  the value of PROFESIONAL.iibb
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getIibb() {
		return iibb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.iibb
	 * @param iibb  the value for PROFESIONAL.iibb
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setIibb(String iibb) {
		this.iibb = iibb == null ? null : iibb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.email
	 * @return  the value of PROFESIONAL.email
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.email
	 * @param email  the value for PROFESIONAL.email
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.password
	 * @return  the value of PROFESIONAL.password
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.password
	 * @param password  the value for PROFESIONAL.password
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.website
	 * @return  the value of PROFESIONAL.website
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.website
	 * @param website  the value for PROFESIONAL.website
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setWebsite(String website) {
		this.website = website == null ? null : website.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.facebookid
	 * @return  the value of PROFESIONAL.facebookid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getFacebookid() {
		return facebookid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.facebookid
	 * @param facebookid  the value for PROFESIONAL.facebookid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setFacebookid(String facebookid) {
		this.facebookid = facebookid == null ? null : facebookid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.facebook
	 * @return  the value of PROFESIONAL.facebook
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getFacebook() {
		return facebook;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.facebook
	 * @param facebook  the value for PROFESIONAL.facebook
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setFacebook(String facebook) {
		this.facebook = facebook == null ? null : facebook.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.businesshours
	 * @return  the value of PROFESIONAL.businesshours
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getBusinesshours() {
		return businesshours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.businesshours
	 * @param businesshours  the value for PROFESIONAL.businesshours
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setBusinesshours(String businesshours) {
		this.businesshours = businesshours == null ? null : businesshours.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.description
	 * @return  the value of PROFESIONAL.description
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.description
	 * @param description  the value for PROFESIONAL.description
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.video1
	 * @return  the value of PROFESIONAL.video1
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVideo1() {
		return video1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.video1
	 * @param video1  the value for PROFESIONAL.video1
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVideo1(String video1) {
		this.video1 = video1 == null ? null : video1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.video2
	 * @return  the value of PROFESIONAL.video2
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVideo2() {
		return video2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.video2
	 * @param video2  the value for PROFESIONAL.video2
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVideo2(String video2) {
		this.video2 = video2 == null ? null : video2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.video3
	 * @return  the value of PROFESIONAL.video3
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVideo3() {
		return video3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.video3
	 * @param video3  the value for PROFESIONAL.video3
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVideo3(String video3) {
		this.video3 = video3 == null ? null : video3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.video4
	 * @return  the value of PROFESIONAL.video4
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVideo4() {
		return video4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.video4
	 * @param video4  the value for PROFESIONAL.video4
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVideo4(String video4) {
		this.video4 = video4 == null ? null : video4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.video5
	 * @return  the value of PROFESIONAL.video5
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVideo5() {
		return video5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.video5
	 * @param video5  the value for PROFESIONAL.video5
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVideo5(String video5) {
		this.video5 = video5 == null ? null : video5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.emailvalid
	 * @return  the value of PROFESIONAL.emailvalid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getEmailvalid() {
		return emailvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.emailvalid
	 * @param emailvalid  the value for PROFESIONAL.emailvalid
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setEmailvalid(Integer emailvalid) {
		this.emailvalid = emailvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.status
	 * @return  the value of PROFESIONAL.status
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.status
	 * @param status  the value for PROFESIONAL.status
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.datachanged
	 * @return  the value of PROFESIONAL.datachanged
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getDatachanged() {
		return datachanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.datachanged
	 * @param datachanged  the value for PROFESIONAL.datachanged
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setDatachanged(Integer datachanged) {
		this.datachanged = datachanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.id_wall
	 * @return  the value of PROFESIONAL.id_wall
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public Integer getIdWall() {
		return idWall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.id_wall
	 * @param idWall  the value for PROFESIONAL.id_wall
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setIdWall(Integer idWall) {
		this.idWall = idWall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROFESIONAL.verifemail
	 * @return  the value of PROFESIONAL.verifemail
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public String getVerifemail() {
		return verifemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROFESIONAL.verifemail
	 * @param verifemail  the value for PROFESIONAL.verifemail
	 * @mbggenerated  Tue Sep 25 23:11:19 ART 2012
	 */
	public void setVerifemail(String verifemail) {
		this.verifemail = verifemail == null ? null : verifemail.trim();
	}

	public String getCompleteName() {
		return this.getFirstname() + " " + this.getLastname();
	}
}