package com.tdil.djmag.model;

import java.util.Date;

public class Newsletter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWSLETTER.id
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWSLETTER.email
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWSLETTER.subscriptiondate
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    private Date subscriptiondate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWSLETTER.id
     *
     * @return the value of NEWSLETTER.id
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWSLETTER.id
     *
     * @param id the value for NEWSLETTER.id
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWSLETTER.email
     *
     * @return the value of NEWSLETTER.email
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWSLETTER.email
     *
     * @param email the value for NEWSLETTER.email
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWSLETTER.subscriptiondate
     *
     * @return the value of NEWSLETTER.subscriptiondate
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public Date getSubscriptiondate() {
        return subscriptiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWSLETTER.subscriptiondate
     *
     * @param subscriptiondate the value for NEWSLETTER.subscriptiondate
     *
     * @mbggenerated Sun Apr 08 11:40:20 ART 2012
     */
    public void setSubscriptiondate(Date subscriptiondate) {
        this.subscriptiondate = subscriptiondate;
    }
}