DROP DATABASE IF EXISTS AAA;
CREATE DATABASE AAA;
GRANT USAGE ON *.* TO 'AAA'@'localhost';
DROP USER 'AAA'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'AAA'@'localhost' IDENTIFIED BY 'AAA_USR';
GRANT ALL ON AAA.* TO AAA_USR IDENTIFIED BY 'AAA_USR';