DROP TABLE IF EXISTS LOVE_NICKNAMES;

CREATE TABLE LOVE_NICKNAMES (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `creationDate` DATETIME NOT NULL ,
  `publishDate` DATETIME NULL ,
  `id_author` INT  NULL ,
  `sex` CHAR(1) NOT NULL ,
  `originalText` VARCHAR(150) NOT NULL ,
  `position` VARCHAR(25) NOT NULL ,
  `approved` INT NOT NULL,
  `id_click_counter` INT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS LINKS;

CREATE TABLE LINKS (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `originType` VARCHAR(150) NOT NULL ,
  `origin` INT NOT NULL ,
  `destinationType` VARCHAR(150) NOT NULL ,
  `destination` INT NOT NULL ,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_LINKS_00` (`originType` ASC, `origin` ASC),
  INDEX `IX_LINKS_01` (`destinationType` ASC, `destination` ASC))
ENGINE = InnoDB;

ALTER TABLE LOVE_NICKNAMES ADD (`url_link` VARCHAR(400) NULL);
ALTER TABLE LOVE_NICKNAMES ADD (`url_target` VARCHAR(50) NULL);

ALTER TABLE WALL_WRITTING ADD (`url_link` VARCHAR(400) NULL);
ALTER TABLE WALL_WRITTING ADD (`url_target` VARCHAR(50) NULL);