package com.tdil.lojack.model;

import com.tdil.ibatis.PersistentObject;

public class AlarmConf extends PersistentObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ALARM_CONF.idEntidad
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	private Integer identidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ALARM_CONF.idWebsiteUser
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	private Integer idwebsiteuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ALARM_CONF.description
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ALARM_CONF.emailNotification
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	private Integer emailnotification;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ALARM_CONF.idEntidad
	 * @return  the value of ALARM_CONF.idEntidad
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public Integer getIdentidad() {
		return identidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ALARM_CONF.idEntidad
	 * @param identidad  the value for ALARM_CONF.idEntidad
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public void setIdentidad(Integer identidad) {
		this.identidad = identidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ALARM_CONF.idWebsiteUser
	 * @return  the value of ALARM_CONF.idWebsiteUser
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public Integer getIdwebsiteuser() {
		return idwebsiteuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ALARM_CONF.idWebsiteUser
	 * @param idwebsiteuser  the value for ALARM_CONF.idWebsiteUser
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public void setIdwebsiteuser(Integer idwebsiteuser) {
		this.idwebsiteuser = idwebsiteuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ALARM_CONF.description
	 * @return  the value of ALARM_CONF.description
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ALARM_CONF.description
	 * @param description  the value for ALARM_CONF.description
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ALARM_CONF.emailNotification
	 * @return  the value of ALARM_CONF.emailNotification
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public Integer getEmailnotification() {
		return emailnotification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ALARM_CONF.emailNotification
	 * @param emailnotification  the value for ALARM_CONF.emailNotification
	 * @mbggenerated  Fri Jul 05 18:38:52 ART 2013
	 */
	public void setEmailnotification(Integer emailnotification) {
		this.emailnotification = emailnotification;
	}
}