package com.tdil.lojack.model;

import com.tdil.ibatis.PersistentObject;

public class SystemUser extends PersistentObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column WEBSITEUSER.guid
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column WEBSITEUSER.id_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	private Integer idAvatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column WEBSITEUSER.ext_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	private String extAvatar;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column WEBSITEUSER.guid
	 * @return  the value of WEBSITEUSER.guid
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column WEBSITEUSER.guid
	 * @param guid  the value for WEBSITEUSER.guid
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column WEBSITEUSER.id_avatar
	 * @return  the value of WEBSITEUSER.id_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public Integer getIdAvatar() {
		return idAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column WEBSITEUSER.id_avatar
	 * @param idAvatar  the value for WEBSITEUSER.id_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public void setIdAvatar(Integer idAvatar) {
		this.idAvatar = idAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column WEBSITEUSER.ext_avatar
	 * @return  the value of WEBSITEUSER.ext_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public String getExtAvatar() {
		return extAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column WEBSITEUSER.ext_avatar
	 * @param extAvatar  the value for WEBSITEUSER.ext_avatar
	 * @mbggenerated  Sun Apr 14 22:47:25 ART 2013
	 */
	public void setExtAvatar(String extAvatar) {
		this.extAvatar = extAvatar == null ? null : extAvatar.trim();
	}
}