package com.tdil.djmag.dao;

import com.tdil.djmag.model.GalleryCategory;
import com.tdil.djmag.model.GalleryCategoryExample;
import java.sql.SQLException;
import java.util.List;

public interface GalleryCategoryDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int countGalleryCategoryByExample(GalleryCategoryExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int deleteGalleryCategoryByExample(GalleryCategoryExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int deleteGalleryCategoryByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    Integer insertGalleryCategory(GalleryCategory record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    Integer insertGalleryCategorySelective(GalleryCategory record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    List<GalleryCategory> selectGalleryCategoryByExample(GalleryCategoryExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    GalleryCategory selectGalleryCategoryByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int updateGalleryCategoryByExampleSelective(GalleryCategory record, GalleryCategoryExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int updateGalleryCategoryByExample(GalleryCategory record, GalleryCategoryExample example) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int updateGalleryCategoryByPrimaryKeySelective(GalleryCategory record) throws SQLException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GALLERY_CATEGORY
     *
     * @mbggenerated Tue Jun 19 18:08:48 ART 2012
     */
    int updateGalleryCategoryByPrimaryKey(GalleryCategory record) throws SQLException;
}