DROP DATABASE IF EXISTS DJMAG;
CREATE DATABASE DJMAG CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT USAGE ON *.* TO 'DJMAG_USER'@'localhost';
DROP USER 'DJMAG_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'DJMAG_USER'@'localhost' IDENTIFIED BY 'DJMAG_USER';
GRANT ALL ON DJMAG.* TO DJMAG_USER IDENTIFIED BY 'DJMAG_USER';