DROP TABLE IF EXISTS GALLERY_CATEGORY;

CREATE TABLE GALLERY_CATEGORY (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `title` VARCHAR(250) NOT NULL ,
  `description` VARCHAR(4000) NULL ,
  `imageExt` VARCHAR(10) NULL,
  `image_id` INT NULL,
  `deleted` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

ALTER TABLE IMAGE_GALLERY ADD (`category_id` INT NULL);
UPDATE IMAGE_GALLERY SET category_id = 0;

COMMIT;