package com.tdil.djmag.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.tdil.djmag.dao.RankingPositionImageDAO;
import com.tdil.djmag.model.RankingPositionImage;
import com.tdil.djmag.model.RankingPositionImageExample;
import java.sql.SQLException;
import java.util.List;

public class RankingPositionImageDAOImpl implements RankingPositionImageDAO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public RankingPositionImageDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int countRankingPositionImageByExample(RankingPositionImageExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("RANKING_POS_IMG.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int deleteRankingPositionImageByExample(RankingPositionImageExample example) throws SQLException {
		int rows = sqlMapClient.delete("RANKING_POS_IMG.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int deleteRankingPositionImageByPrimaryKey(Integer id) throws SQLException {
		RankingPositionImage _key = new RankingPositionImage();
		_key.setId(id);
		int rows = sqlMapClient.delete("RANKING_POS_IMG.deleteByPrimaryKey", _key);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public Integer insertRankingPositionImage(RankingPositionImage record) throws SQLException {
		Object newKey = sqlMapClient.insert("RANKING_POS_IMG.insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public Integer insertRankingPositionImageSelective(RankingPositionImage record) throws SQLException {
		Object newKey = sqlMapClient.insert("RANKING_POS_IMG.insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	@SuppressWarnings("unchecked")
	public List<RankingPositionImage> selectRankingPositionImageByExample(RankingPositionImageExample example)
			throws SQLException {
		List<RankingPositionImage> list = sqlMapClient.queryForList("RANKING_POS_IMG.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public RankingPositionImage selectRankingPositionImageByPrimaryKey(Integer id) throws SQLException {
		RankingPositionImage _key = new RankingPositionImage();
		_key.setId(id);
		RankingPositionImage record = (RankingPositionImage) sqlMapClient.queryForObject(
				"RANKING_POS_IMG.selectByPrimaryKey", _key);
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int updateRankingPositionImageByExampleSelective(RankingPositionImage record,
			RankingPositionImageExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("RANKING_POS_IMG.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int updateRankingPositionImageByExample(RankingPositionImage record, RankingPositionImageExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("RANKING_POS_IMG.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int updateRankingPositionImageByPrimaryKeySelective(RankingPositionImage record) throws SQLException {
		int rows = sqlMapClient.update("RANKING_POS_IMG.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	public int updateRankingPositionImageByPrimaryKey(RankingPositionImage record) throws SQLException {
		int rows = sqlMapClient.update("RANKING_POS_IMG.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RANKING_POS_IMG
	 * @mbggenerated  Fri May 18 00:05:45 ART 2012
	 */
	protected static class UpdateByExampleParms extends RankingPositionImageExample {
		private Object record;

		public UpdateByExampleParms(Object record, RankingPositionImageExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}